# Generated by Django 4.2.16 on 2024-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlfoodfinder', '0002_remove_favorite_users_favorite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='placeid',
            field=models.BigIntegerField(default=0),
        ),
    ]
